export enum typeCart {
    ADD_TO_CART = 'ADD_TO_CART',
    ADD_TO_CART_ACTION = 'ADD_TO_CART_ACTION',
    REMOVE_FROM_CART_ACTION = 'REMOVE_FROM_CART_ACTION',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    EMPTY_CART = 'EMPTY_CART',
    PRODUCT_LIST = 'PRODUCT_LIST',
    SET_PRODUCT_LIST = 'SET_PRODUCT_LIST'
}